name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  

      - name: Install AWS CLI
        run: |
          pip install awscli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Replace with your AWS region

      - name: Run unit tests
        run: |
          python transformation_unit_test.py  

      - name: Upload Glue Script to S3
        if: success()  
        run: |
          aws s3 cp silver_transformed_all.py s3://emeka-market-raw-sales-data/scripts/silver_transformed_all.py 

      - name: Start Glue Job
        if: success()  
        run: |
          aws glue start-job-run --job-name your-glue-job-name  # Replace with your Glue job name
